### ISSUE TITLE
Please activate your account?

### ISSUE THREAD

**Issue by Webreaper** [superdanio/expressvpn#14]
So I can't connect at all. My docker-compose:
```
 expressvpn:
        container_name: expressvpn
        image: superdanio/expressvpn
        environment:
          - ACTIVATION_CODE={redacted}
          - CONNECT_AT_STARTUP=true
        cap_add:
          - NET_ADMIN
        devices: 
          - /dev/net/tun
        stdin_open: true
        tty: true
        privileged: true
        restart: unless-stopped
        volumes:
          - /volume1/dockerdata/expressvpn:/vpn_shared
        ports:
          - 4998:5000 # exposing API port
          - 8090:8090
          - 6881:6881
          - 6881:6881/udp
          - 8080:8080
          - 9117:9117
          - 9696:9696
```

I just get this:

<img width="1060" alt="Image" src="https://github.com/user-attachments/assets/354ba5dd-2efe-4d3c-b73f-4addff11ab18" />

This is running on a Synology NAS. Any ideas?
